# config/schema/easytransac.schema.yml
easytransac.commerce_payment_gateway.plugin.easytransac_redirect_checkout:
  type: commerce_payment_gateway_configuration
  mapping:
    private_key:
      type: string
      label: 'Private key'
    api_key:
      type: string
      label: 'API key'